### ISSUE TITLE
sqlite3 error when running _starting_with_frbpoppy_.py

### ISSUE THREAD

**Issue by KshitijAggarwal** [davidgardenier/frbpoppy#40]
I followed these steps, and got the following error: 

```
>> conda create -n frbpoppy python=3.8
>> conda activate frbpoppy
>> git clone https://github.com/davidgardenier/frbpoppy.git 
>> cd frbpoppy
>> python3 setup.py develop
>> python3 examples/_starting_with_frbpoppy_.py 
cosmic_pop.py | Generating complex population
Traceback (most recent call last):
  File "examples/_starting_with_frbpoppy_.py", line 14, in <module>
    cosmic_pop.generate()
  File "/hyrule/data/users/kshitij/frbpoppy/frbpoppy/cosmic_pop.py", line 499, in generate
    self.gen_dist()
  File "/hyrule/data/users/kshitijfrbpoppy/frbpoppy/cosmic_pop.py", line 126, in gen_dist
    n_model = self.dist_func()
  File "/hyrule/data/users/kshitij/frbpoppy/frbpoppy/cosmic_pop.py", line 122, in <lambda>
    self.dist_func = lambda: NumberDensity(model=model, **kwargs)
  File "/hyrule/data/users/kshitij/frbpoppy/frbpoppy/number_density.py", line 31, in __init__
    m = self.dt(z=np.array([z_max]))
  File "/hyrule/data/users/kshitij/frbpoppy/frbpoppy/precalc.py", line 352, in lookup
    d = c.execute(query, [str(r)]).fetchone()
sqlite3.OperationalError: disk I/O error
```

**Comment by davidgardenier** [comment]
Given the error is a disk I/O error, I would presume this might have to do with limited disk space or memory issues.

Do you have write permissions and enough space ( ~100MB) in memory / on the drive you're trying to access? (```frbpoppy/data/models/universe```)

Hope this helps, but otherwise I would recommend checking Stackoverflow for 'SQL disk I/O error' and seeing which case is applicable to you.

**Comment by KshitijAggarwal** [comment]
It wasn't a disk space issue, but I somehow got it working.

**Comment by davidgardenier** [comment]
Excellent to hear!
